pages/urls.py
from django.urls import path
from pages.views import ContactView, Result, detailPage

app_name = 'pages'

urlpatterns = [
    path('', ContactView.as_view(), name = 'index'),
    path('search/query=<str:query>', Result.as_view(), name = 'query'),
    path('search/details/<int:fdcId>', detailPage, name = 'detailPage'),
]

webpage/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('overview/',views.OverviewPage.as_view(),name ='overview'),
    path('help/',views.HelpPage.as_view(), name = 'help'),
    path('',include('pages.urls', namespace = 'pages'))
]

pages/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms

class NutritionForm(forms.Form):
    query = forms.CharField(max_length = '100',
                            label = '',
                            widget=forms.TextInput(attrs =
                                                    {'placeholder': 'Search for food or FDC ID or UPC',
                                                    'size':80,'autocomplete':'off',
                                                    'style': 'height: 50px;'
                                                            'width: 600px;'
                                                            'border-radius:8px solid grey;'
                                                            'padding: 7px; margin-top: 10px;'
                                                            'margin-bottom: 10px; font-size: 15px;'}))

pages/views.py
from django.shortcuts import render
from . import forms
import requests
import json
from django.views.generic import ListView, FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.conf import settings
import logging
from webpage.settings import base

import pdb

class ContactView(FormView):
    """
    This view gives form for entering search input(fooditem).
    Once the form is submitted, it validates and redirect to result page.
    """
    logging.basicConfig(level = logging.DEBUG, format = '%(asctime)s - %(levelname)s - %(message)s')

    template_name = 'index.html'
    form_class = forms.NutritionForm
    context_object_name = 'search_results'

    def form_valid(self, form, **kwargs):
        self.term = form.cleaned_data['query']
        self.request.session['word_searched'] = form.cleaned_data['query']
        return super().form_valid(form, **kwargs)

    def get_success_url(self):
        return reverse_lazy("pages:query", kwargs = {'query':self.term})



class Result(ListView):

    """
    Calls the helper method to get the results as list view.
    Results are paginated.
    """
    template_name = 'result.html'
    paginate_by = 10
    context_object_name = 'search_results'
    search_results = []

    def get_queryset(self):
        self.food = self.kwargs.get('query')
        self.search_results = SearchHelper.search(self, self.food)
        return self.search_results

    def get_context_data(self, **kwargs):
        if len(self.search_results) == 0:
            context = {
            'paginator': None,
            'page_obj': None,
            'is_paginated': False,
            'search_results': []
            }
            logging.debug("got valid results with count: " + str(len(self.search_results)))
            context['search_result_length'] = len(self.search_results)
            len(self.search_results)

        else:
            context  = super(Result, self).get_context_data()
            context['search_result_length'] = len(self.search_results)
            context['search_results'] = self.search_results
            return context

class SearchHelper(object):
    """
    This class makes the API call to fetch the results for search keyword
    """
    def search(self, food):
        headers = {
            'X-Api-Key': base.API_KEY
        }

        url = settings.LIST_URL
        params = {
                'query': food,
                'pageNumber': 1,
                'pageSize':100,
        }

        logging.debug("the query url is: " + str(url))

        response = requests.request("GET", url, headers = headers, params = params)
        data = response.json()
        return data

def detailPage(request,fdcId):
    """
    This function renders the detail elements in the list.
    """
    result = {}
    headers = {
        'X-Api-Key': base.API_KEY
    }

    url = settings.DETAIL_URL + str(fdcId)

    logging.debug("the url for detail page is: " + url)

    response = requests.request("GET", url, headers = headers)
    data = response.json()
    result = data

    return render(request, 'detail.html', {'result': result})

webpage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexPage(TemplateView):
    template_name = 'index.html'

class OverviewPage(TemplateView):
   template_name = 'overview.html'

class HelpPage(TemplateView):
    template_name = 'help.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'basic.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>
       {% block title %} {% endblock title %}
     </title>
       {% block scripts %} {% endblock scripts %}


  </head>
  <body>

    <div class="container navbar-nav">
  <div class="nav-wrapper ">
    <div class="left-side">
      <div class="nav-link-wrapper nav-item active">
          <a href="{% url 'pages:index' %}">Home</a></div>
    <div class="nav-link-wrapper ">
        <a href="{% url 'overview' %}">About</a>
    </div>
    <div class="nav-link-wrapper ">
        <a href="{% url 'help' %}">Help</a>
    </div>

    </div>

    </div>

      </div>




    {% block content %}
    {% endblock content%}

  </body>
  <script src="static/test.js" charset="utf-8"></script>
  {% block js %}

{% endblock js %}
</html>

templates/detail.html
{% extends 'base.html'%}
{% load static %}

{% block content%}
<link rel="stylesheet"  href="{% static 'css/basic.css' %}" />

<div class ='container'  >
  <h3>{{term}}</h3>
  <h4>Serving size : {{result.servingSize}}{{result.servingSizeUnit}}</h4>
  <pre class='tab'><h4><td><em>FDCID:{{result.fdcId}}</em></td>  <td><em>Brand Owner: {{result.brandOwner}}</em></td>  <td><em>GTIN/UPC:{{result.gtinUpc}}</em></td>
  <td><em>Market Country: {{result.marketCountry}}</em></td> <td><em>Branded Food Category:{{result.brandedFoodCategory}}</em></td></h4></pre>
</div>

<div class = 'container' align = 'center'>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Unit</th>
      <th>Deriv. by</th>
    </tr>
{% for data in result.foodNutrients %}
<tr>
  <td>{{data.nutrient.name}}</td>
  <td>{{data.amount}}</td>
  <td>{{data.nutrient.unitName}}</td>
  <td>{{data.foodNutrientDerivation.description}}</td>
</tr>
{% endfor %}

  </table>
  </div>


{% endblock content %}

templates/empty.html
{% extends 'base.html'%}

{% block body_block%}
<h2>no results found:{{form.food}} </h2>

{% endblock %}

templates/help.html
{%extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3>Key Terms and Concepts</h3>

<h5>Search Results</h5>
<h6>Search Results Pages</h6>
<p>The pages listing all the foods that match the search criteria entered by the user and that provide nutrient and related information for a specific food.
Identifying and Categorizing Food Items
FDC_ID Number
This is the number provided for each food data record in FoodData Central. A food record is the totality of information (e.g., nutrient or food component value, descriptive information) published on a food item. Each time the data in a food record changes, that food item receives a new FDC_ID number.
FDC Source_ID Number
This is the FDC_ID number that identifies the record of a unique sample of a food that has been analyzed for one or more nutrients or food components.
NDB Number
This number is a unique identifier for each food in Foundation Foods and SR Legacy. Even if the FDC_ID number changes because of an update to the food record, the NDB number will remain the same because it is linked to the food, not to the information about the food. Users can search for a food item by the name of the food or the NDB number.
Global Trade Item Number (GTIN)
The GTIN is a number that can be used by a company to uniquely identify their trade items. It is used to identify specific food items in the USDA Global Branded Foods Database. Users can search for a food item by the name of the food or the GTIN number.
Food Code
An 8-digit number that identifies foods in FNDDS. These foods are used in analyses of NHANES dietary data. Users can search for a food in FNDDS either by its name or its food code.
Food Category
A method for classifying similar foods. Each data type has its own system of food categories.
Characteristics of Nutrient and Food Component Values
Min
The smallest amount of a nutrient or food component found in an analyzed sample of a food item.
Max
The greatest amount of a nutrient or food component found in an analyzed sample of a food item.
Median
The amount of a nutrient or food component that is at the midpoint of all the amounts in the samples analyzed for a food item.
Average Amount
The amount of a nutrient or food component derived by summing the amounts for each analyzed sample, which may include the mean of multiple determinations of the sample, and then dividing by the number of samples.
Updates to Food Data
Information about the foods in FoodData Central is updated periodically. At the current time, only the USDA Global Branded Foods Database allows users to see changes to the data in this data type. The search results page will include an Update Log tab for those foods that have been updated. This tab will appear next to the Nutrients tab and users can learn about specific changes by clicking on this tab. The log will list one or more previous food records for that food item (i.e., “an historical food record”). Each of these historical food records will detail the specific change. These changes can be any one of the following:

Description changed
Food category changed
Ingredient changed
Nutrient value changed
Nutrient added
Nutrient removed
Serving size changed
Users can compare the current food record to the historical food record by clicking on the historical record. This will bring up a new browser window allowing users to see the records side by side.

Tips for Online Searching
Conducting a Search
A search on FoodData Central involves four steps:

Step 1:  Use the Search FoodData Central box, which is found on each page of the website. You can search for a current item by its name or by one of the numbers that uniquely identifies that item within a specific FDC data type (e.g., NDB number, FNDDS Food Code, or GTIN number).
Step 2: Use the “Filter Search Results” on the left side of the screen to select the data type you want to search. The numbers in parentheses after the data type indicate the number of foods in that type related to your search. If you want to search all of the data types, leave all the boxes checked. If you want to search one or more specific data types, unselect the boxes next to the data type you do not want to include in the search. Click Search.
Step 3: You will see a Search Results page that provides a list of items from the data type(s) you selected. Click on the item that best matches the food you are interested in.
Step 4: A more detailed search results page provides nutrient and other food component values, portion size information, and other information about the item and how the data were derived.
For more information on searching FoodData Central using downloads, see the Download Data page.

Using Search Operators
You can use symbols in your search to make your search results more precise.

Search for an exact phrase
Quotation marks search for an exact phrase:
"green pepper" will only match green pepper products, not anything with the word “green” or “pepper” in it.

Require words
+ (plus sign) makes a word required:
candy corn matches all foods with “candy” or “corn”.

+candy corn matches only foods that have “candy” and weighs the foods that have “corn” higher than those that don’t.

+candy +corn matches only foods that have both “candy” and “corn”.

Exclude words
- (minus sign) excludes foods having the word:</p>

  </div>


{% endblock content%}

templates/index.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/basic.css' %}"/>
{% block content %}

<div style="padding:15px;text-align:center;">
  <h1>FOOD CALORIE COUNTER</h1>
</div>


<br>

<div class="container" >

    <h6>Calories provide the energy that your body needs to function and stay alive.

While there is no evidence to support that negative-calorie foods burn more calories than they provide, foods that are already low in calories may actually provide fewer calories than expected. This is because your body uses energy to digest them.</h6>
</div>
<div class="container">
    <form  method="post">
        <input type="text" name="query" placeholder="Search for food or FDC ID or UPC" autocomplete='off'>
        {% csrf_token %}

         <button type="submit"><i class="fa fa-search"></i></button>

    </form>
  </div>
  <br>
  <br>
<div class="container">

<div class="content-wrapper">
      <div class="row portfolio-items-wrapper">

        <div class="col-sm-4 portfolio-item-wrapper select1">
          <div class="portfolio-img-background"style= "background-image: url(static/images/food.jpeg)"></div>

          <div class="img-text-wrapper">


              <div class="subtitle subtitle1">
                Did you know!!
                The Yubari melon is the world's most expensive fruit.
              </div>



          </div>
        </div>
        <div class="col-sm-4 portfolio-item-wrapper select2">
          <div class="portfolio-img-background"style= "background-image: url(static/images/fruits.jpeg)"></div>

          <div class="img-text-wrapper">

              <div class=" subtitle subtitle2">
                Kiwi fruit contains more vitamin C than oranges.
              </div>



          </div>

        </div>
          <div class="col-md-4 portfolio-item-wrapper select3">
            <div class="portfolio-img-background"
            style= "background-image: url(static/images/vegan.jpeg)"></div>
            <div class="img-text-wrapper">

                <div class="subtitle subtitle3">
                  Did you Know!!!
                  Potatoes were the first vegetable to be grown in space.
                </div>

            </div>

            </div>
            </div>
            </div>
          </div>


{% endblock content %}

templates/overview.html
{%extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{%static '/css/change.css' %}">
<br>
<article >
<div class="container">
<h2>Tell Me More about FoodCalorie Counter</h2>
<dl>
  <dt>
  What is FoodCalorie Counter?
</dt>
<dd>
<p>FoodCalorie Counter is an integrated, research-focused data system that provides expanded data on nutrients and other foods components as well as links to sources of related agricultural, food, dietary supplement, and other information. FoodCalorie Counter can be used by, and has benefits for, a variety of users, including educators, nutrition and health professionals,and others.</p></dd>
<dt>
  Why FoodCalorie Counter is launched ?
</dt>
<dd>
  <p>The food supply is constantly changing and evolving, with new products and formulations continuously introduced into the marketplace and other products being removed. Moreover, ingredients and raw agricultural products are also constantly changing. In addition, current thinking about the role of diet, health, and wellness is moving beyond a focus on single nutrients to encompass foods, food groups, and dietary patterns.</p>

<p>These diverse trends have implications for research, food policy, dietary guidance, and product development. They are creating a growing number of uses for data about food and an urgent need for transparent and easily accessible information about the nutrients and other components of foods and food products. This need required a new approach to analyzing, compiling, and presenting food profile information in a scientifically rigorous way. FoodData Central embodies this new approach and will provide expanded food and experimental data and additional functionality as the system continues to develop.</p>
</dd>
</dl>




</div>
</article>

    <!-- <div class="container">
        <p>Food name:  {{ food }}</p>
    </div> -->


{% endblock content %}

templates/result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet"  href="{% static 'css/board.css' %}"/>
  <br>
<div class = 'container'>
  <h3 align ="center">You searched for "{{ request.session.word_searched }}"</h3>

  {% if search_result_length is null %}
  {% else %}
    <h6>{{ search_result_length }} results found matching {{ request.session.word_searched }}</h6>
   {% endif %}

<table id = "myTable" align= "center" class="table table-striped table-hover container tablesorter">
  <thead>
    <tr>
      <th>FDCID</th>
      <th>DESCRIPTION</th>
      <th>BRAND OWNER</th>
      <th>PUBLISHED DATE</th>
    </tr>
  </thead>
  <tbody>

   {% for result in search_results %}
    <tr>
      <td><a href="details/{{result.fdcId}}">{{result.fdcId}}</a></td>
      <td><a href="details/{{result.fdcId}}">{{result.description}}</a></td>
      <td><a href="details/{{result.fdcId}}">{{result.brandOwner}}</a></td>
      <td><a href="details/{{result.fdcId}}">{{result.publicationDate}}</a></td>
    </tr>
    {% endfor%}
  </tbody>
</table>
</div>


{% endblock content%}



{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#myTable').DataTable({searching: false, info: false});
} );
</script>
</div>
{% endblock %}